# Generated by Django 5.2.8 on 2025-12-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='custom_salutation',
            field=models.CharField(blank=True, max_length=100, verbose_name='Freie Anrede'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_custom_salutation',
            field=models.BooleanField(default=False, verbose_name='Individuelle Anrede'),
        ),
        migrations.AddField(
            model_name='customer',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(max_length=50, verbose_name='Stadt'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Firmenname'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_number',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='Kundennummer'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('Privat', 'Privat'), ('Firma', 'Firma')], default='Privat', max_length=10, verbose_name='Kundentyp'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Vorname'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='house_number',
            field=models.CharField(max_length=10, verbose_name='Hausnummer'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nachname'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='postal_code',
            field=models.CharField(max_length=10, verbose_name='PLZ'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='salutation',
            field=models.CharField(blank=True, choices=[('', '---'), ('Herr', 'Herr'), ('Frau', 'Frau'), ('Divers', 'Divers')], default='', max_length=20, verbose_name='Anrede'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='street',
            field=models.CharField(max_length=50, verbose_name='Straße'),
        ),
    ]
