# Generated by Django 5.2 on 2025-08-12 09:49

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('invoice_number', models.CharField(max_length=20, unique=True)),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('apartment_name', models.CharField(max_length=100)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=8)),
                ('breakfast_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=Decimal('7.00'), max_digits=5)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
    ]
