# Generated by Django 5.2.5 on 2025-08-12 10:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='include_breakfast',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='breakfast_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
