# Generated by Django 5.2.8 on 2025-11-22 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoice_include_breakfast_and_more'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='apartment_name',
        ),
        migrations.AddField(
            model_name='invoice',
            name='rental_property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.property', verbose_name='Ferienwohnung'),
        ),
    ]
