# Generated by Django 5.2.8 on 2025-11-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_invoice_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='docx_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
    ]
