# Generated by Django 5.2.8 on 2025-12-27 11:58

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_custom_salutation_and_more'),
        ('invoices', '0005_invoice_docx_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='arrival_date',
            field=models.DateField(verbose_name='Anreisedatum'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='breakfast_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=8, verbose_name='Preis für Frühstück'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='Kunde'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Rechnungsdatum'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='departure_date',
            field=models.DateField(verbose_name='Abreisedatum'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='docx_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/', verbose_name='Word Datei'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='include_breakfast',
            field=models.BooleanField(default=False, verbose_name='Frühstück inklusive'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Rechnungsnummer'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/', verbose_name='PDF Datei'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preis pro Nacht'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('7.00'), max_digits=5, verbose_name='Steuersatz (%)'),
        ),
    ]
