# Generated by Django 5.2.8 on 2025-11-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_subscription',
            field=models.BooleanField(default=False, verbose_name='Hat Abo'),
        ),
    ]
