# Generated by Django 5.2.8 on 2025-11-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name der Ferienwohnung')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preis pro Nacht')),
                ('default_breakfast_price', models.DecimalField(decimal_places=2, default=10.0, max_digits=8, verbose_name='Standard Frühstückspreis')),
                ('default_tax_percent', models.DecimalField(decimal_places=2, default=7.0, max_digits=5, verbose_name='Standard MwSt. Satz')),
            ],
            options={
                'verbose_name': 'Ferienwohnung',
                'verbose_name_plural': 'Ferienwohnungen',
            },
        ),
    ]
